# -------------------------
# Stage 1: Build React app
# -------------------------

FROM node:22-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci

COPY frontend ./

ARG VITE_API_URL

ENV VITE_API_URL=${VITE_API_URL}

RUN npm run build


# -------------------------
# Stage 2: Serve with Nginx
# -------------------------

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 5174

CMD ["nginx", "-g", "daemon off;"]